### ISSUE TITLE
Annotated variable names that begin with class emit bad code

### ISSUE THREAD

**Issue by euresti** [hhatto/autopep8#365]
This is related to https://github.com/PyCQA/pycodestyle/issues/716

```
class Foo:
    classification: int
    definition: int
    _def: int
    _class: int


def foo():
    class_foo: int
    def_value: int
```

results in 
```
class Foo:
    classification:
        int
    definition: int
    _def: int
    _class: int


def foo():
    class_foo:
        int
    def_value: int
```

Weird that `def` isn't affected.
