### ISSUE TITLE
ignores #noqa comment that pydocstyle doesn't

### ISSUE THREAD

**Issue by dcbaker** [hhatto/autopep8#602]
## Python Code
```python
def func(a: object, b: object) -> bool:
    return type(a) is type(b)  # noqa
```

## Command Line and Configuration
pyproject.toml

```toml
[tool.autopep8]
max_line_length = 120
in-place = true
recursive = true
aggressive = 1
```

Command Line
```shell
$ pydocstyle test.py
# everything is fine, type comparison properly ignored
$ autopep8 test.py
# changes `type(a) is type(b)` to `isinstance(a, type(b))`
```

## Your Environment
* Python version: 3.6.13
* autopep8 version: autopep8 1.5.4 (pycodestyle: 2.6.0)
* Platform: windows, linux, macOSX, and other OS...: linux
