### ISSUE TITLE
add pre-commit configuration here?

### ISSUE THREAD

**Issue by asottile** [hhatto/autopep8#678]
👋 current we maintain for [pre-commit](https://pre-commit.com) a [mirror for autopep8](https://github.com/pre-commit/mirrors-autopep8) -- would it make sense to add a pre-commit configuration here such that people can reach the repository more directly?

it shouldn't need too much maintenance -- the mirror repo hasn't really changed since onset -- basically this yaml file in the root of the repo would suffice:

```yaml
# .pre-commit-hooks.yaml
-   id: autopep8
    name: autopep8
    entry: autopep8
    language: python
    types: [python]
    args: [-i]
```

I could then deprecate the mirror repo and point people here
